services:
  db:
    image: postgres:15-alpine
    container_name: linkia-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: linkia
      POSTGRES_PASSWORD: password
      POSTGRES_DB: linkia-db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
